---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: athene-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: athene-server
    spec:
      containers:
        - name: athene-server
          image: 'sebastianstehle/athene-server:1'
          imagePullPolicy: Always
          env:
          - name: GCE_STORAGE_BUCKETNAME
            value: athene-diagram-files
  revisionHistoryLimit: 2
---
apiVersion: v1
kind: Service
metadata:
  name: athene-server
  labels:
    name: athene-server
spec:
  ports:
    - port: 80
      targetPort: 4000
  selector:
    app: athene-server
  type: LoadBalancer
